version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name kadai4-deploy --s3-location s3://kadai4-bucket/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src